// Release 0
// to write a function that takes an array of words or phrases and retuns the longest word or phrase in the array.
// set a VARIABLE that is equal to a STRING of words/phrases separated by commas.
	// SORT the strings in the order of the length.
// RETURN the last string in the array


var array = ["long phrase","longest phrase","longer phrase"];

function longest_phrase(some_array) {
	array.sort(function(a, b){return a.length-b.length});
	longest_word = array[array.length - 1];
	console.log(longest_word)
}

longest_phrase(array)

// Release 1
// to write a function that takes two objects and checks to see if the objects share at least one key-value pair.
// input: Object1 and Object2
// Code:
	// assign elements into object 1
	// assign elements into object 2
	// for EACH key in object1, check if it equals a key in object 2.
	// IF object1 key = object2 key, return true
	// ELSE return false
// output: boolean value of true or false


function name(first_object, second_object){
	var object1 = first_object;
	var object2 = second_object;
	for (var key in object1) {
		if (object1[key] = object2[key]) {
			console.log(true)
		}
		else {
			console.log(false)
		}
	}
}

name({name: "Steven", age: 54}, {name:"Tamir", age: 54})

// Release 2
// to write a function that takes an integer for length, and builds and returns an array of strings of the given length.
// input:
	// an integer
// code:
	// Create empty array
	// UNTIL the length of the array is equal to entered integer
		// create a random string generated by letters. 
// output:
	// an array with length of the integer from the input, and with random strings between the length of 1 to 10 letters. 

function string_array(integer) {
	var text = ""
	var array = []
	var possible_letters = "abcdefghijklmnopqrstuvwxyz"

	for( var i=0; i < 11; 1++ )
		text += possible_letters.charAt(Math.floor(Math.random() * possible_letters.length));

	var array = array.push(text)
}


random_string(3)
= ["aadfa", "adjlk;", "adjk;la"]